// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE
'use strict';

var Yawaramin__Dbc = require("./Yawaramin__Dbc.bs.js");

function safeDiv(num, denom) {
  Yawaramin__Dbc.pre("num >= denom", num >= denom);
  Yawaramin__Dbc.pre("denom != 0", denom !== 0);
  return Yawaramin__Dbc.post("safeDiv(num, denom) *. denom == num", (function (result) {
                  return result * denom === num;
                }))(num / denom);
}

console.log(safeDiv(3, 2));

var Dbc = 0;

exports.Dbc = Dbc;
exports.safeDiv = safeDiv;
/*  Not a pure module */
