// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function contract(pre, post, body) {
  pre.forEach(function (param) {
        if (param[1]) {
          return ;
        }
        throw new TypeError("Precondition broken: " + param[0]);
      });
  post(body).forEach(function (param) {
        if (param[1]) {
          return ;
        }
        throw new TypeError("Postcondition broken: " + param[0]);
      });
  return body;
}

function noPost(param) {
  return function (param) {
    return [];
  };
}

function pre(messageOpt, condition) {
  var message = messageOpt !== undefined ? messageOpt : "(no description)";
  if (condition) {
    return ;
  }
  throw new TypeError("Precondition broken: " + message);
}

function post(messageOpt, func) {
  var message = messageOpt !== undefined ? messageOpt : "(no description)";
  return function (result) {
    if (func(result)) {
      return result;
    }
    throw new TypeError("Postcondition broken: " + message);
  };
}

exports.contract = contract;
exports.noPost = noPost;
exports.pre = pre;
exports.post = post;
/* No side effect */
