// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE
'use strict';


function pre($staropt$star, condition) {
  var message = $staropt$star !== undefined ? $staropt$star : "(no description)";
  if (condition) {
    return 0;
  } else {
    var message$1 = "Precondition broken: " + (String(message) + "");
    throw new TypeError(message$1);
  }
}

function post($staropt$star, func) {
  var message = $staropt$star !== undefined ? $staropt$star : "(no description)";
  return (function (result) {
      if (func(result)) {
        return result;
      } else {
        var message$1 = "Postcondition broken: " + (String(message) + "");
        throw new TypeError(message$1);
      }
    });
}

exports.pre = pre;
exports.post = post;
/* No side effect */
